services:
  postgres:
    image: postgres:14
    container_name: crypto-wallet-postgres
    environment:
      POSTGRES_DB: crypto_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: